### PR TITLE
My changes to where.js

### PR DESCRIPTION
**Pull request by dlowry14**

### CODE REVIEW

**Comment by cengebretson** [comment]
Think I would prefer a regExp approach, something like this...

```
var functionCall = /\$\$(\w+)\((.*?)\)/; 
if (var match = funcationCall.exec(v)) {
  var functionName    = match[1];
  var functionParams = match[2].split(',');
  // clean up params
  functionParams       = functionParams.map( function(value) { JSON.parse(value.trim()); } )
```

**Comment by dlowry14** [comment]
Okay, I've never worked with regEx is that functionally equivalent or does it need more added yet?

**Comment by cengebretson** [comment]
its built into javascript

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

just regular expressions, here is a good site to see how they work https://www.regex101.com/#javascript

**Comment by cengebretson** [comment]
looks good! thanks dave, sorry so late in getting this in.

**Pull request merged**
